export default {
login: "GAURAVKR007",
id: 84225690,
node_id: "MDQ6VXNlcjg0MjI1Njkw",
avatar_url: "https://avatars.githubusercontent.com/u/84225690?v=4",
gravatar_id: "",
url: "https://api.github.com/users/GAURAVKR007",
html_url: "https://github.com/GAURAVKR007",
followers_url: "https://api.github.com/users/GAURAVKR007/followers",
following_url: "https://api.github.com/users/GAURAVKR007/following{/other_user}",
gists_url: "https://api.github.com/users/GAURAVKR007/gists{/gist_id}",
starred_url: "https://api.github.com/users/GAURAVKR007/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/GAURAVKR007/subscriptions",
organizations_url: "https://api.github.com/users/GAURAVKR007/orgs",
repos_url: "https://api.github.com/users/GAURAVKR007/repos",
events_url: "https://api.github.com/users/GAURAVKR007/events{/privacy}",
received_events_url: "https://api.github.com/users/GAURAVKR007/received_events",
type: "User",
site_admin: false,
name: "Gaurav Kumar Thakur",
company: null,
blog: "",
location: "INDIA",
email: null,
hireable: null,
bio: "Programming really feels like magic where they speak some spells and something amazing happen. Just like that i write some code and something amazing happen.",
twitter_username: "GauravKrThakur2",
public_repos: 127,
public_gists: 0,
followers: 8,
following: 9,
created_at: "2021-05-15T08:57:13Z",
updated_at: "2023-11-30T21:51:53Z"
};
